language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirement.txt
  - pip install coveralls

script:
  - nosetests -v --with-coverage --cover-package="Tests"
  
after_success: 
- coveralls
