language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirement.txt
  - pip install coveralls

script:
  - coverage run -m unittest Tests/test_register.py -v
  - coverage report -m
after_success: 
- coveralls
