language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirement.txt
  - pip install coveralls

script:
  - python -m unittest -v Tests/test_register.py
  
after_success: 
- coveralls
